-- AlterTable
ALTER TABLE `promo` ADD COLUMN `maxRedeem` INTEGER NULL,
    MODIFY `type` ENUM('INFORMATION', 'REDEEM_POINTS', 'EXCLUSIVE_MEMBER', 'FREE_BENEFIT_NEW_REG', 'EVENT') NOT NULL DEFAULT 'INFORMATION';
