-- AlterTable
ALTER TABLE `promo` ADD COLUMN `pointsRequired` INTEGER NULL,
    ADD COLUMN `type` ENUM('INFORMATION', 'REDEEM_POINTS', 'EXCLUSIVE_MEMBER', 'FREE_BENEFIT_NEW_REG') NOT NULL DEFAULT 'INFORMATION';
