-- AlterTable
ALTER TABLE `user` ADD COLUMN `adminRole` ENUM('CASHIER', 'MODERATOR', 'OWNER', 'SUPER_ADMIN') NULL,
    ADD COLUMN `fullName` VARCHAR(191) NULL,
    ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;
